### ISSUE TITLE
Issue when starting prometheus container on rpi

### ISSUE THREAD

**Issue by pvardanega** [napnap75/rpi-prometheus#7]
`
ERRO[0000] Invalid command line arguments. Help: /bin/prometheus -h  source="config.go:275"
ERRO[0000] flag provided but not defined: -storage.tsdb.path  source="main.go:74"
`

This is due to the fact that the image is built from [prometheus master](https://github.com/prometheus/prometheus/blob/master/Dockerfile) with is compatible with prometheus 2.x, not 1.x.

There are at least two solutions:

- building the image for prometheus 2.x,
- building the image from the 1.x Dockerfile (which needs a bit of boilerplate code in travis.yml because the problem is not there for node_exporter). To apply this solution, you'll also need to revert this [pull request](https://github.com/napnap75/rpi-prometheus/pull/6)

**Comment by napnap75** [comment]
Closed with #9
